- name: Ansible Playbook to Install and Setup Apache on Ubuntu
  hosts: all
  become: yes
  tasks:
    - name: Install latest version of Apache 2222
      apt: name=apache2 update_cache=yes state=latest
    - name: Install latest version of wget
      apt: name=wget update_cache=yes state=latest
      
    - name: Install latest version of git
      apt: name=nginx update_cache=yes state=latest
 
    - name: Create document root for domain configured in host variable
      file:
        path: "/var/www/index.html"
        state: directory
        owner: www-data
        group: www-data
        mode: '0755'
 
  handlers:
    - name: restart-apache
      service:
        name: apache2
        state: restarted
